name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install requirements, excluding large ML libs if possible for faster CI
        # For now, install all. Consider splitting requirements later.
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        # Install test-specific dependencies if any (e.g., unittest mocks)
        # pip install ...

    - name: Run unit tests
      run: |
        python -m unittest discover tests

